### ISSUE TITLE
XML data format

### ISSUE THREAD

**Issue by AnWang-AI** [racerandom/JaMIE#1]
Thanks for your great work.
The first step is to convert XML files to CONLL files for Train/Test. 
However, I don't know what's the XML data format for this step.
Could you give an annotated simple example?
Thank you very much.

**Comment by racerandom** [comment]
Thank you for your interest.
I share the annotation guideline link here:

-  [English guideline](https://sociocom.naist.jp/real-mednlp/wp-content/uploads/sites/3/2021/10/Real-MedNLP_Annotation_Guidelines_English.pdf )

- [Japanese guideline](https://sociocom.naist.jp/real-mednlp/wp-content/uploads/sites/3/2021/07/PRISM_Annotation_Guidelines.pdf)

A [simple example](https://github.com/racerandom/JaMIE/blob/demo/demo_files.zip) is available.
